project:
  type: website
  output-dir: _site

  # bibliography: references.bib
csl: apa7.csl
# keep-tex: true
date-format: "DD MMMM, YYYY"
website:
  title: "Materials for PS52007D Research Methods in Psychology"
  description: "Materials for PS52007D Research Methods in Psychology at Goldsmiths, University of London"
  site-url: "https://ps52007dslides.littlemonkeylab.com"
  bread-crumbs: false


  repo-url: https://github.com/LittleMonkeyLab/PS52007Dslides/
  repo-actions: [edit, issue]

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd

  sidebar:
    logo: "images/rmmonkey.png"
    style: docked
    collapse-level: 3
    search: false
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Coursework"
        href: index.qmd
        contents:
          - index.qmd
          - index.qmd
          - index.qmd
      - section: "Lectures"
        contents:
          - text: "Week 01 Lecture"
            href: week01/lecture.qmd
          - text: "Week 02 Lecture"
            href: week02/lecture.qmd
          - text: "Week 03 Lecture"
            href: week03/lecture.qmd
      - section: "Labs"
        contents:
          - text: "Week 01 Lab"
            href: week01/lab.qmd
          - text: "Week 02 Lecture"
            href: week02/lab.qmd
          - text: "Week 03 Lecture"
            href: week03/lab.qmd


  page-footer:
    right: |
      "This page is built with {{< fa brands r-project >}}, ☕,❤️and [Quarto](https://quarto.org/) <br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/littlemonkeylab/ps52007dslides.com)
    left: |
      Content {{< fa brands creative-commons >}} 2024 by gordon wright {{< fa brands orcid >}} <strong>ORCID</strong> [0000-0001-9424-5743](https://orcid.org/0000-0001-9424-5743). All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} {{< fa brands creative-commons-sa >}}<br>
      [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)



format:
  html:
    theme: cosmo
    linkcolor: "#325b74" # Pantone Midnight - Fall 2022
    mainfont: "Atkinson Hyperlegible"
    comments:
      hypothesis: true

  revealjs:
    theme: styles/slides.scss
    logo: "/images/LMLLOGO.png"
    header-logo: "/images/rmmonkey.png"
    menu: true
    controls: true
    navigation-mode: linear
    controls-layout: edges
    show-slide-number: all
    slide-number: c/t
    mainfont: Atkinson Hyperlegible
    incremental: false
    margin: 0.1
    smaller: false
    pdf-page-height-offset: -2
    max-width: 90%
    max-scale: 2.0
    pdf-max-pages-per-slide: 1
    output-ext: slides.html
    hide-from-titleSlide: "text"
    embed-resources: true
    filters:
      - fontawesome
      - reveal-header

  pptx:
    reference-doc: _resources/templates/pptx/PS52007D.pptx


editor: visual
engine: knitr

execute:
  freeze: auto
