project:
  type: website
  bibliography: references.bib
  csl: apa7.csl
# keep-tex: true

website:
   sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - lectureshub.qmd
          - preludeshub.qmd
          - extrashub.qmd
          
  google-analytics: ""
  page-navigation: true
  title: "Materials for PS52007D Research Methods in Psychology"
  description: "Materials for PS52007D Research Methods in Psychology at Goldsmiths, University of London"
  site-url: "https://ps52007dslides.littlemonkeylab.com"

  repo-url: https://github.com/LittleMonkeyLab/PS52007Dslides/
  repo-actions: [edit, issue]

  opengraph: true
  twitter-card:
    creator: "@DrDeception"
    image: "images/twitter-card.png"
  

  page-footer:
    right: "This page is built with ☕,❤️and [Quarto](https://quarto.org/)."
    left: |
      Content {{< fa brands creative-commons >}} 2022 by gordon wright. All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} {{< fa brands creative-commons-sa >}}<br>
      [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)
    background: "#6699CC"

format:
  html:
    theme:
      light: [cosmo, style/light.scss]
      dark: [cosmo, style/light.scss, style/dark.scss]
    linkcolor: "#325b74" # Pantone Midnight - Fall 2022
    mainfont: "Atkinson Hyperlegible"
    comments:
      hypothesis: true

  # pdf:
  #   # template: templates/eisvogel.tex
  #   geometry:
  #     - top=30mm
  #     - left=30mm
  # docx: default
  #
  #   # toc: true
  #   # toc-depth: 3
  #   # mainfont: "Atkinson Hyperlegible"
  #   # sansfont: "Atkinson Hyperlegible"
  #   # linkcolor: blue
  #   # links-as-notes: true
  #   # papersize: a4
  #   # reference-links: true
  #   # template: /templates/eisvogel.tex
  # revealjs:
  #   theme: _resources/templates/Lectures_RM.scss
  #   mainfont: Atkinson Hyperlegible
  #   self-contained: true
  #   incremental: false
  #   margin: 0.2
  #   smaller: false
  #   output-ext: htm
  # pdf:
  #   template: _resources/templates/latex.tex
  #   # template: _resources/templates/latex-colour.tex
    # pdfengine: lualatex
    # fontsize: 12pt # 10, 11, or 12pt
    # mainfont: Atkinson Hyperlegible # font used for main text throughout document
    # sansfont: Atkinson Hyperlegible
    # classoption: landscape
    # papersize: a4
    # pagestyle: empty
    # cosmiclatte: false # set true to turn on an off-white page background colour
  # html:
  # #   template: _resources/templates/html.html
  #
  # pptx:
  #   reference-doc: _resources/templates/pptx/RMLecturepptxTemplate.pptx


editor: visual
