name: Render and Publish
on:
  push:
    branches:
      - main  # changes pushed to this branch will trigger a build.

jobs:
  build-deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: "Setup pandoc"
        uses: r-lib/actions/setup-pandoc@v2

      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2

      # Pinned shinylive dependency
      - name: "Setup R dependencies for Quarto's knitr engine"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            cran::shinylive@0.1.1
            any::knitr
            any::rmarkdown
            any::downlit
            any::xml2

      # Setup Quarto
      - name: "Set up Quarto"
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.554

      # Install quarto extensions
      - name: "Install quarto extension for shinylive and quarto-webr"
        shell: bash
        run: |
          quarto add --no-prompt quarto-ext/shinylive
          quarto add --no-prompt coatless/quarto-webr@0.4.2

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages # renderred html files will be pushed here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
